---
- name: Test for Grafana and Prometheus
  hosts: main
  gather_facts: no
  tasks:
    - name: Grafana Test
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}:3000
        follow_redirects: none
        status_code: [302]
    - name : Prometheus Test
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}:9090
        follow_redirects: none
        status_code: [302]

        
